Pass the tests for v1.3 branch
Pass the tempest basic network scenario tests for branch v1.3.
Rellocate the git ssh key check to 'functions' script.
Use web.xml.dev as midonet-api service configuration file

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -4,6 +4,13 @@ function is_devstack_cloned() {
     MIDO_DIR=$(pwd)
     DEVSTACK_DIR="$MIDO_DIR/devstack"
     if [ ! "$(ls -A $DEVSTACK_DIR)" ]; then
+        # Check access to github.com
+        ssh -T -o StrictHostKeyChecking=no git@github.com
+        [ $? == 255 ] && {
+            echo "Exiting. Can't authenticate with Github via ssh; please check that your ssh key is present in ~/.ssh."
+            exit 1
+        }
+
         git submodule update --init
     fi
 }
